### ISSUE TITLE
How to tell analytics.js to use proxy-url instead?

### ISSUE THREAD

**Issue by vkovalskiy** [segmentio/segment-proxy#1]
Hi, I can't find a way to instract analytics.js to use segment-proxy address rather then default segmen.io address. How to do it ?

**Comment by f2prateek** [comment]
Can you explain your use case?

**Comment by f2prateek** [comment]
Also for general support questions, please write in via https://segment.com/contact.

**Comment by vkovalskiy** [comment]
@f2prateek segment support said that they do not officially support segment-proxy so I'm writing here - Ok, we've hosted segment-proxy on our server. Now, how to load analytics.js to use our proxy instead of default segment location (which is blocked by ad-blocker)?

**Comment by f2prateek** [comment]
This is not meant for circumventing ad blockers.

**Comment by vkovalskiy** [comment]
@f2prateek sorry, then I can't get the idea on how to use your proxy. Ok, we are launching it locally. How to tell analytics.js route through this proxy ? Or what is the typical use case this sproxy was written for ?
